### ISSUE TITLE
Datenbank erstellen und mit Daten füllen

### ISSUE THREAD

**Issue by MrNomNom98** [Dennis2512/DiseaseFinder#5]
Nachdem das DBS steht und eine Verbindung zwischen Server und DBS existiert muss eine Datenbank anhand der von dem Crawler gezogenen Daten erstellt werden und die Daten gespeichert werden
@Dennis2512 Wo finde ich hierzu die vom Crawler gezogenen Daten?

**Comment by Dennis2512** [comment]
Datenbank wurde auf englisch und auf deutsch mit 450 Krankheiten befüllt.
